### PR TITLE
Migration of nutritionist diet plan

### PR DESCRIPTION
**Pull request by tommasini**
- [x] Nutritionist Diet plan

### CODE REVIEW

**Comment by Andree37** [comment]
I don't know whether this approach of inserting all the files is better than 1 by 1 as needed.

I believe its easier to identify that some of the things we have are clearly nothing. E.g. the api folder, some of the libraries, etc.

If you choose to do 1 by 1, I think now is still a good time, if you choose to go this way, I am afraid of what will happen when we decide to remove all of the 'wrong code'

just food for thought!

**Comment by Andree37** [comment]
I don't know whether this approach of inserting all the files is better than 1 by 1 as needed.

I believe its easier to identify that some of the things we have are clearly nothing. E.g. the api folder, some of the libraries, etc.

If you choose to do 1 by 1, I think now is still a good time, if you choose to go this way, I am afraid of what will happen when we decide to remove all of the 'wrong code'

just food for thought!

**Comment by Andree37** [comment]
We need to test the SWR mutation on the delete diet plan to ensure that we have immediate response.

Or else, we need to resort to sending the state from father to child, which should also be okay, but I was expecting this work nicely 😢

**Comment by Andree37** [comment]
@tommasini why are we getting netlify stuff?

**Comment by tommasini** [comment]
Netlify stuff? No, why do you ask that?

**Comment by Andree37** [comment]
we have a netlify bot on this PR and also some commit checks that are only here because of netlify, what is this? @tommasini

**Comment by tommasini** [comment]
Ah it's like a ci of netlify we need to remove the netlify package

**Comment by Andree37** [comment]
ah okidoki, lets be sure to remove it :D

**Pull request closed without merging**
